### ISSUE TITLE
Documentation on customisation of chainkit.yaml and running apps in general

### ISSUE THREAD

**Issue by ruseinov** [blocklayerhq/chainkit#14]
Currently there's not much in documentation department, so every time one wants to change the way sample app works it's necessary to dig into the code to figure that out.

It would be really nice to get some docs explaining the basics and customisation points.

**Comment by samalba** [comment]
It's a fair point, I'll add some doc on this.

**Comment by samalba** [comment]
Fixed with 1bcd1289c9f026c5ea10d9eb59cfe74a4c795dd2
