### ISSUE TITLE
Unable to create network : invalid cross-device link on chainkit start

### ISSUE THREAD

**Issue by shikharfb** [blocklayerhq/chainkit#19]
I have been trying to start the Chainkit application on my localhost.
The build is working okay so far. But when I do `chainkit start`, it throws an error:
```
✗ unable to create network: 
link /home/shikhar/go/src/github.com/fbchain-app/chainkit.yml /tmp/chainkit-network087127657/chainkit.yml: 
invalid cross-device link

```

Is this an issue with application path or something else while building?

Because i don't see any file named as `chainkit.yml` in `/tmp/chainkit-network087127657`

**Comment by samalba** [comment]
Can you give some more data about what you use?

Local system, version of docker, command you type.

I think the file in /tmp is inside the container, that's why you don't see it.

**Comment by shikharfb** [comment]
Hey, thanks. 
It was in the container itself.

**Comment by yash-fb** [comment]
I am facing the same issue. I tried copying the `chainkit.yml` file to the ` tmp/chainkit-networkxxxxxx` but it doesn't work because every time I execute `chainkit start` it spins up a new container which is again missing the 'chinkit.yml'.
