### ISSUE TITLE
doesn't start

### ISSUE THREAD

**Issue by bill-th2** [blocklayerhq/chainkit#2]
==> Starting contracts
==> Initializing node...
generating 4096-bit RSA keypair...done
peer identity: QmesQDK4zzsDULvNfRkdojDT9ovEDTtEH74v17WWZD1Sy3
==> Generating configuration and genesis files
Unable to find image 'chainkit-contracts:latest' locally
docker: Error response from daemon: pull access denied for chainkit-contracts, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Unable to find image 'chainkit-contracts:latest' locally
docker: Error response from daemon: pull access denied for chainkit-contracts, repository does not exist or may require 'docker login'.
See 'docker run --help'.
✗ initialization failed: exit status 125

**Comment by bill-th2** [comment]
Never mind, it had to do with setting docker permissions correctly. It won't run with sudo, so you have to add yourself to docker group.

**Comment by samalba** [comment]
Indeed, chainkit assumes the current user has access to the docker daemon.
